### ISSUE TITLE
Compiling on NetBSD 9.2

### ISSUE THREAD

**Issue by reginaldbuxley** [spkr-beep/beep#22]
Let me know if this is a NetBSD issue and not valid to post here.

When trying to compile, per the INSTALL.md 
```
make
make install
```

make can not 'see' the make file. When using the -f option and using GNUMakefile, a plethora of errors spit out (mostly regarding Needing an operator). 

Here is what I get when running `file` on `make`. I could not seem to get it to say it's version. Perhaps it does not. 
`ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /usr/libexec/ld.elf_so, for NetBSD 9.2, not stripped`

GCC version:
`gcc (nb4 20200810) 7.5.0`

Anyone know what I can do here?

**Comment by ndim** [comment]
The `GNUmakefile` is called that because it requires GNU make, so other make implementations such as BSD make will not work (as the "plethora of errors" makes clear). I have seen BSD systems which have a GNU make executable named `gmake`, but read on before you try that.

However, `beep` has been written explicitly as a user command line interface to the Linux kernel API for beeping the PC speaker. I would expect non-Linux kernels to have very different APIs, so beep will not work there.

As to whether it is possible (and whether it makes sense) to add drivers for non-Linux kernels to the beep source code, I do not know right off the top of my head.

**Comment by ndim** [comment]
After doing some research, I now presume you are confusing this `beep` with a BSD command `beep` like e.g. [FreeBSD beep(1)](https://www.freebsd.org/cgi/man.cgi?query=beep) or perhaps the reimplementation of this beep's ancestor for OpenBSD/NetBSD at https://github.com/jnlon/beep.

As for porting this `beep` to run on BSD by writing a new driver for BSD APIs, I have looked into the [FreeBSD speaker(4)](https://www.freebsd.org/cgi/man.cgi?query=speaker&apropos=0&sektion=4&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html) and [NetBSD speaker(4)](https://man.netbsd.org/speaker.4) APIs. These APIs are higher level than the Linux APIs are, so this would require a partial rewrite of this `beep`'s core and the driver interface (Linux API: "start beeping with this frequency or stop beeping right now", BSD speaker(4) API: "beep with this frequency for this duration", or even "beep with this sequence of (frequency, duration) tuples until the end of the list").

That kind of rewrite is certainly feasible, but right now I do not see the point.

**Comment by ndim** [comment]
@reginaldbuxley Ping?

**Comment by reginaldbuxley** [comment]
Sounds good enough to me. Thanks.
