### ISSUE TITLE
need to run modprobe

### ISSUE THREAD

**Issue by bradrh1** [spkr-beep/beep#25]
beep wouldn't work at all for me until I ran
```sudo modprobe pcspkr```

I didn't see any mention of this in the documentation.

Xubuntu 20.04

**Comment by ndim** [comment]
Thank you for noticing and reporting!

**Comment by redtux** [comment]
Hi @ndim, I am having the same issue on Ubuntu 20.04.3 LTS, but even after running `sudo modprobe pcspkr` it is not working. I can get `beep` to make some noise, but no beep…

Apart from this I noticed that `/lib/udev/rules.d/70-pcspkr-beep.rules` references to a group `beep` (as mentioned in `PERMISSIONS.md`), but this group is not being created by the post-install script.

```bash
$ lsmod | grep pcspkr
pcspkr                 16384  0

$ grep -c beep /etc/group
0
```

**Comment by ndim** [comment]
As I have a VM running Ubuntu 21.04, I have just installed the `beep` package and checked that the `beep` group is indeed not being created:

    $ sudo apt install beep
    $ getent group beep
    $ _

However, the `/lib/udev/rules.d/70-pcspkr-beep.rules` file shipped by the `beep-1.4.9-1build1` package does not use a `beep` group (or any other group) anyway for its way allowing access to the device file:

```
# Give write access to the PC speaker to "beep" group so they can run "beep"
ACTION=="add", SUBSYSTEM=="input", ATTRS{name}=="PC Speaker", ENV{DEVNAME}!="", TAG+="uaccess"
```

I cannot check whether the `uaccess` rule actually works, because I only have ssh access to the Ubuntu VM, so I am never logged in as a local user which is what the `uaccess` `TAG` is handling.

That is why I suggest in `PACKAGING.md` (and `PERMISSIONS.md`) that distribution packages create a `beep` group to make granting access to more users as easy as adding a user to the `beep` group for those users who are not covered by `TAG+="uaccess"`. The Fedora beep package does exactly that, because I maintain that.

However, last time I was in contact with the maintainer of the Debian package, they decided not to follow all of my suggestions, and I remember that I was expecting users having unnecessary permission problems resulting directly from that decision. I cannot remember the exact details off the top of my head. However, when I examine the beep package in my Debian 10 VM, that package appears to use a purely `TAG+="uaccess"` based approach, and the Ubuntu 21.04 package appears to not differ from the Debian 10 package in that regard at all.

I maintain the upstream beep software, and in that capacity I propose a permission setup which should cover most use cases (both `TAG+="uaccess"` and `GROUP="beep"`) for most distributions, and I maintain the Fedora `beep` package which demonstrates that this proposed permission setup works.

As far as the Debian/Ubuntu packages are concerned, those are outside of my immediate area of influence. You will need to talk to the Debian/Ubuntu package maintainers (i.e. file a bug with Debian/Ubuntu) and persuade them if you want the Debian/Ubuntu package to change to the hybrid group+tag approach.

@redtux As your problem with the permission setup is unrelated to documenting the need to run `modprobe`, please file a new issue if the documentation for permission setup can be improved here in the upstream package.

**Comment by redtux** [comment]
Alright, thank you for clarification! Just stumbled across this issue while looking for my problem, and thought others might be interested when reading this.

FYI @rhonda :)

**Comment by rhonda** [comment]
@redtux Thanks for bringing it up to my attention.  I'm sorry that I have been mostly unresponsive in recent times, I'm trying to fix that and bring the package up to pace again. At the time of when this was first brought up time schedules were pretty tight and under pressure and thus I was rather objecting to do further changes right away. I was musing to revisit it after a while when I had a clearer head to spin it around the issue but this clearly never happened yet ...

Said that, @ndim - if I want to give the uaccess plus the group access through setfacl, is that possible in a single line, or would I need two separate ones for that? e.g. having TAG+= and RUN+= in the same udev line should work?

One more packaging background why I refrained from going that path back then: beep couldn't simply add acl as package dependency because beep creates an installer package, while acl didn't, and I wasn't sure about the issues relating to not having setfacl available in the installer but having the udev rule using it. acl does now also create an installer package so that path is now also covered.

**Comment by ndim** [comment]
> Said that, @ndim - if I want to give the uaccess plus the group access through setfacl, is that possible in a single line, or would I need two separate ones for that? e.g. having TAG+= and RUN+= in the same udev line should work?

As far as I know, more than one action in a single udev should work.

I cannot remember off the top of my head why I chose two separate rules in separate rule files. Might have had something to do with the two priorities (70 vs 90), or documentation being easier with separate rules in separate files. Actually, this is a good question. I will need to take a more in depth look here.

> One more packaging background why I refrained from going that path back then: beep couldn't simply add acl as package dependency because beep creates an installer package, while acl didn't, and I wasn't sure about the issues relating to not having setfacl available in the installer but having the udev rule using it. acl does now also create an installer package so that path is now also covered.

TBH, I had not seen a distribution without ACL in some time back then, so I naturally wrote the example group permission setup using `RUN="setfacl ..."` at first in order to have a rule working independently of what `TAG+=` eventually achieves in terms of ownership and permission bits.

However, after become aware of Debian not having setfacl installed by default, I added added an example rule which uses `GROUP="beep", MODE="0620"`. Perhaps MODE="g+w" also works, without needing to touch the other parts of the permission flags.

So if you know that `TAG+="uaccess"` works on Debian by affecting the user part of the owner, and the user parts of the permission bits, using `GROUP=` and `MODE=` to affect the group parts sounds like a perfectly reasonable way to achieve both tag and group access without dealing with the availability of setfacl.

I will do a few experiments later today.

**Comment by ndim** [comment]
OK, so... some results (tested on my Fedora 35 system):

  * `TAGS+="uaccess", GROUP="beep", MODE="g+w"` works, resulting in `0660` because the default permissions are `0660` anyway
  * `TAGS+="uaccess", GROUP="beep", MODE="0620"` works , resulting in `0660`. WTH?
  * `TAGS+="uaccess", GROUP="beep", MODE="0220"` works, resulting in `0260`. WTH?
  * `TAGS+="uaccess", RUN+="/usr/bin/setfacl -m g:beep:w '$env{DEVNAME}'"` works, resulting in
    ```
    # file: dev/input/by-path/platform-pcspkr-event-spkr
    # owner: root
    # group: input
    user::rw-
    user:user:rw-
    group::rw-
    group:beep:-w-
    mask::rw-
    other::---
    ```

So, answering the question on combining more than one action in one udev rule: Yes, that works.

However, if you want to disable one of those actions, you need to write a new udev rules file and put it in /etc/udev/rules.d. If you have different rules in different files and you want to maybe disable the `TAG+="uaccess"` rule from /usr/lib/udev/rules.d/90-beep.rules while keeping the `beep` group rules from /usr/lib/udev/rules.d/90-beep.rules active, you can just "ln -s /dev/null /etc/udev/rules.d/90-beep.rules` to disable the rules from /usr/lib/udev/rules.d/90-beep.rules.

Conclusion: I can still stand by what I have written in `PERMISSIONS.md` and recommend having two separate rule files, one for the `TAG+="uaccess"` and allowing group write access, the latter using `setfacl` if ACLs can be counted on, or `GROUP=` otherwise.
